name: trigger gitlab job
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: echo
      run: |
        echo ${{ vars.PROJECT_GIT_LAB_URL }}
        echo ${{ vars.PROJECT_GIT_LAB_ID }}

    - name: trigger Job
      uses: appleboy/gitlab-ci-action@master
      with:
        url: ${{ vars.PROJECT_GIT_LAB_URL }} 
        token: ${{ secrets.GIT_LAB_TOKEN }}
        project_id: ${{ vars.PROJECT_GIT_LAB_ID }}