name: trigger gitlab job
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: ls public repo
      run: |
        env

    - name: trigger Job
      uses: appleboy/gitlab-ci-action@master
      with:
        url: "https://gitlab.linnovate.net" 
        token: ${{ secrets.GIT_LAB_TOKEN }}
        project_id: 2902 