name: trigger gitlab job
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: echo
      run: |
        echo ${{ vars.PROJECT_GIT_LAB_URL }}
        echo ${{ vars.PROJECT_GIT_LAB_ID }}

    - name: trigger Job
      uses: digital-blueprint/gitlab-pipeline-trigger-action@v1
      with:
        host: ${{ vars.PROJECT_GIT_LAB_URL }} 
        trigger_token: ${{ secrets.DEPLOY_TRIGGER_TOKEN_GITLAB }}
        access_token: ${{ secrets.DEPLOY_ACCESS_TOKEN_GITLAB }}
        id: ${{ vars.PROJECT_GIT_LAB_ID }}
        ref: 'master'
