name: test

on:
  pull_request:
    branches: [ main ] 
    
env:
  #BUILD_NUMBER: ${{ github.run_number }} 

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3

      - name: Increment build number and ouput release
        run: |
          #creating build number and release version
          BUILD_NUMBER=$(cat ./app/version.properties | head -n 1 | tail -n 1 | sed -r 's/^[^0-9]*([0-9]+).*/\1/')
          MINOR_VERSION=$(cat ./app/version.properties | head -n 2 | tail -n 1 | sed -r 's/^[^0-9]*([0-9]+).*/\1/')
          MAJOR_VERSION=$(cat ./app/version.properties | head -n 3 | tail -n 1 | sed -r 's/^[^0-9]*([0-9]+).*/\1/')
          BUILD_NUMBER=$((BUILD_NUMBER+1))
          echo "BUILD_NUMBER = $BUILD_NUMBER"
          echo "Release v = $MAJOR_VERSION.$MINOR_VERSION.$BUILD_NUMBER"
          #replace build number in the file
          REPLACE=$((BUILD_NUMBER-1))
          sed -i "s/BUILD_VERSION=$REPLACE/BUILD_VERSION=$BUILD_NUMBER/g" ./app/version.properties
              
      - name: Create Release Tag
        uses: actions/create-release@v1
        with:
          tag_name: v${{ MAJOR_VERSION }}.${{ MINOR_VERSION }}.${{ BUILD_NUMBER" }}
          release_name: Release v${{ MAJOR_VERSION }}.${{ MINOR_VERSION }}.${{ BUILD_NUMBER" }}


      - name: Commit files
        run: |
          #git config --local user.email "egorikftp@gmail.com"
          #git config --local user.name "egorikftp"
          git commit -m "Increment build version" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
