name: test

on:
  pull_request:
    branches: [ main ] 
    
env:
  BUILD_NUMBER: ${{ github.run_number }} # default variable GITHUB_RUN_NUMBER

jobs:
  build:
    name: Test Build 
    runs-on: ubuntu-latest

    steps:
      - name: Print BUILD_NUMBER-${{ env.BUILD_NUMBER }}
        run: echo "BUILD_NUMBER-${{ env.BUILD_NUMBER }}.apk"
      
      - uses: actions/checkout@v3
      
      - name: Create Tag
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v.0.0.${{ github.run_number }}
          release_name: Release v.0.0.${{ github.run_number }}

      - name: Upload APK preprod
        uses: actions/upload-artifact@v2
        with:
          name: app-debug-${{ github.run_number }}.apk
          path: ./app-debug-${{ github.run_number }}.apk
        
     - name: Upload APK preprod
        uses: actions/upload-artifact@v2
        with:
          name: app-debug-${{ github.run_number }}.apk
          path: ./app-release-v.0.0.${{ github.run_number }}.apk