name: test

on:
  push:
    branches: [ testing ] 
     
env:
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest


    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3
        
      - name: ls public repo
        run: |
          ls 

      - name: Add "android-keystore" repo
        uses: actions/checkout@v3
        with:
          repository: Ivanouski1/github_action_test
          token: ${{ secrets.GH_PAT }} # GH_PAT=Personal_Acces_Token (scope repo)
          path: android-keystore
          
          
      - name: ls after private repo (Copy amplify config files)
        run: |
          echo "ls"
          ls 
          echo "ls full path "
          ls android-keystore/amplify-keys/raw
          cat android-keystore/amplify-keys/raw/test1.json >> app/file1.txt
          cat android-keystore/amplify-keys/raw/test1.json >> app/file2.txt
          cat app/file1.txt
          cat app/file2.txt

         
 

