name: test

on:
  push:
    branches: [ testing ] 
     
env:
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest


    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3
        
      - name: ls public repo
        run: |
          ls 

      - name: Checkout amplifyconfiguration.json
        uses: actions/checkout@v3
        with:
          repository: Ivanouski1/github_action_test
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: amplify-keys
          
          
      - name: ls after private repo (Copy amplify config files)
        run: |
          echo "ls"
          ls 
          echo "ls amplify-keys"
          ls amplify-keys
          

         
 

