name: test

on:
  push:
    branches: [ testing ] 
    
#env:
  #BUILD_NUMBER: ${{ github.run_number }} 

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3

      - name: Increment build number and ouput release
        run: ./increment.sh
        shell: bash
      
      - name:
        run: echo $BUILD_NUMBER
              
 #     - name: Create Release Tag
 #       uses: actions/create-release@v1
 #       with:
 #         tag_name: v${{ MAJOR_VERSION }}.${{ MINOR_VERSION }}.${{ BUILD_NUMBER" }}
 #         release_name: Release v${{ MAJOR_VERSION }}.${{ MINOR_VERSION }}.${{ BUILD_NUMBER" }}


      - name: Commit files
        run: |
          git config --local user.email "Andrei_Ivanouski1@epam.com"
          git config --local user.name "Ivanouski1"
          git commit -m "Increment build version" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
