name: test

on:
  push:
    branches: [ testing ] 
    
#env:
  #BUILD_NUMBER: ${{ github.run_number }} 

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3

      - name: Increment build number and ouput release
        run: ./increment.sh
        shell: bash
      

              
      - name: Create Release Tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}
          release_name: Release v${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}


      - run: sudo mkdir -p /artifact

      - run: sudo echo hello > /artifact/test.txt

      - run: mv /artifact/test.txt /artifact/test-{{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: /artifact/test-{{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}.txt


      - name: Commit files
        run: |
          git config --local user.email "Andrei_Ivanouski1@epam.com"
          git config --local user.name "Ivanouski1"
          git commit -m "Increment build version" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
