name: test

on:
  pull_request:
    branches: [ main ] 

env:
  BUILD_NUMBER: ${{ github.run_number }} # default variable GITHUB_RUN_NUMBER

jobs:
  build:
    name: Test Build Number
    runs-on: ubuntu-latest

    steps:
      - name: Print BUILD_NUMBER-${{ env.BUILD_NUMBER }}
        run: echo "test-${{ env.BUILD_NUMBER }}.apk"


      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./package.json
