name: test

on:
  push:
    branches: [ testing ] 
     

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest


    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3

      - name: Checkout folder from private repo
        uses: actions/checkout@v3
        with:
          repository: my-org/my-tools
          path: my-tools
          
      - name: Increment build number and ouput release
        run: ./increment.sh
        shell: bash
      
      - name: create arifact
        run: |
          echo "hello" >> ./app/test.txt

      - name: Rename artifacts
        run: |
          mv ./app/test.txt ./app/test-${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}.txt

      - uses: actions/upload-artifact@v3
        with:
          name: test-${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}.txt
          path: ./app/test-${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}.txt

#      - name: Create Release Tag
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: v${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}
#          release_name: Release v${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}

      - name: Create release Tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./app/test-${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}.txt
          tag: v${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}
          name: Release v${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Commit files
        run: |
          git config --local user.email "Andrei_Ivanouski1@epam.com"
          git config --local user.name "Ivanouski1"
          git commit -m "Increment build version" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

###
