name: test

on:
  push:
    branches: [ testing ] 
     
env:
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest


    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3
        
      - name: ls public repo
        run: |
          ls 

      - name: Checkout amplifyconfiguration.json
        uses: actions/checkout@v3
        with:
          repository: Ivanouski1/github_action_test
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: github_action_test/android-keystore/amplify-keys/raw/test1.json
          
      - name: Checkout awsconfiguration.json
        uses: actions/checkout@v3
        with:
          repository: Ivanouski1/github_action_test
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: github_action_test/android-keystore/amplify-keys/raw/test2.json
          
      - name: ls after private repo (Copy amplify config files)
        run: |
          ls ./github_action_test/android-keystore/amplify-keys/raw
          cat ./github_action_test/android-keystore/amplify-keys/raw/test1.json >> ./app/file1.txt
          cat ./github_action_test/android-keystore/amplify-keys/raw/test2.json >> ./app/file2.txt
          cat ./app/file1.txt 
          cat ./app/file2.txt
          

         
 

