name: test

on:
  push:
    branches: [ testing ] 
     
env:
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest


    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3
        
      - name: ls public repo
        run: |
          ls 

      - name: Checkout folder from private repo
        uses: actions/checkout@v3
        with:
          repository: Ivanouski1/github_action_test
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: github_action_test/android-keystore/amplify-keys/raw
          
      - name: ls after private repo
        run: |
          ls ./github_action_test/android-keystore/amplify-keys
          ls ./github_action_test/android-keystore/amplify-keys/raw
          
     # - name: Copy amplify config files
      #  run: |
       #   cat ./github_action_test/android-keystore/amplify-keys/raw/test1.json >> ./app/test1.txt
        #  cat ./github_action_test/android-keystore/amplify-keys/raw/test2.json >> ./app/test2.txt
         # cat ./app/test1.txt
          #cat ./app/test2.txt
         
 

