name: test

on:
  push:
    branches: [ testing ] 
     
env:
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest


    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3

      - name: Checkout folder from private repo
        uses: actions/checkout@v3
        with:
          repository: Ivanouski1/github_action_test
          ref: main
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: android-keystore/amplify-keys/raw/*
          
      - name: Copy amplify config files
        run: |
          ls android-keystore/amplify-keys/raw/
          cat android-keystore/amplify-keys/raw/test1.json >> ./app/test1.txt
          cat android-keystore/amplify-keys/raw/test2.json >> ./app/test2.txt
          cat app/test1.txt
          cat app/test2.txt
          
      - name: Increment build number and ouput release
        run: ./increment.sh
        shell: bash
      
      - name: create arifact
        run: |
          echo "hello" >> ./app/test.txt

      - name: Rename artifacts
        run: |
          mv ./app/test.txt ./app/test-${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}.txt

      - uses: actions/upload-artifact@v3
        with:
          name: test-${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}.txt
          path: ./app/test-${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}.txt


      - name: Create release Tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./app/test-${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}.txt
          tag: v${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}
          name: Release v${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.BUILD_NUMBER }}
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Commit files
        run: |
          git config --local user.email "Andrei_Ivanouski1@epam.com"
          git config --local user.name "Ivanouski1"
          git commit -m "Increment build version" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

